### ISSUE TITLE
Firmware patch to extract RSSI and SNR

### ISSUE THREAD

**Issue by ghufranbaig** [seemoo-lab/talon-tools#2]
I was able to successfully port your framework to the Talon AD7200 that I have. I am able to run the hello world patch.
However I am not sure on how to go from here to building the patch that enables me to get RSSI and SNR for each packet. Can you please give me some pointers. And if its possible can you please share code for the patch with me.

**Comment by dsteinmetzer** [comment]
We just added new examples to the nexmon-arc project that allows to extract that information.
